name: Github Page

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  github-page:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        env :
          CI: true
        run: |
          npm pkg delete scripts.prepare
          npm ci

      - name: Run build Github Page
        run: |
          npm run github

      - name: Deploy GitHub Page
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: dist